### ISSUE TITLE
mac部署出错

### ISSUE THREAD

**Issue by Rudyy898** [Ice-Cirno/HoshinoBot#115]
FileNotFoundError: [Errno 2] No such file or directory: './res/img/priconne/comic/index.json'
机器人没反应酷q正常

**Comment by Rudyy898** [comment]
ERROR: <class 'FileNotFoundError'> occured when doing scheduled job update_seeker.
[2020-06-29 16:55:25,003 pcr-comic] ERROR: [Errno 2] No such file or directory: './res/img/priconne/comic/index.json'
Traceback (most recent call last):
  File "/Users/admin/Documents/HoshinoBot/hoshino/service.py", line 324, in wrapper
    ret = await func()
  File "/Users/admin/Documents/HoshinoBot/hoshino/modules/priconne/comic.py", line 106, in update_seeker
    index = load_index()
  File "/Users/admin/Documents/HoshinoBot/hoshino/modules/priconne/comic.py", line 21, in load_index
    with open(R.get('img/priconne/comic/index.json').path, encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './res/img/priconne/comic/index.json'

**Comment by Ice-Cirno** [comment]
请下载资源包
