### ISSUE TITLE
抽卡时图片发送错误

### ISSUE THREAD

**Issue by yuban01652** [Ice-Cirno/HoshinoBot#137]
在抽卡时，有时会遇到报错，但是发setu却没有影响，不知为啥

以下为hoshino端的报错：
[2020-08-03 13:46:34,732 gacha] ERROR: <class 'aiocqhttp.exceptions.ActionFailed'> occured when gacha_300 handling message 71497.
[2020-08-03 13:46:34,732 gacha] ERROR: <ActionFailed, retcode=103>
Traceback (most recent call last):
  File "/root/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await sf.func(bot, event)
  File "/root/HoshinoBot/hoshino/modules/priconne/gacha/__init__.py", line 219, in gacha_300
    await bot.send(ev, '\n'.join(msg), at_sender=True)
  File "/usr/local/python3/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 256, in send
    return await self.send_msg(**params)
  File "/usr/local/python3/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 223, in call_action
    return await self._api.call_action(action=action, **params)
  File "/usr/local/python3/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 186, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "/usr/local/python3/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 161, in call_action
    return _handle_api_result(
  File "/usr/local/python3/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 51, in _handle_api_result
    raise ActionFailed(retcode=result.get('retcode'))
aiocqhttp.exceptions.ActionFailed: <ActionFailed, retcode=103>

以下为mirai端的报错
 13:46:18 [INFO] [NETWORK] Send: ImgStore.GroupPicUp
 13:46:18 [INFO] [NETWORK] Recv: RequireUpload(fileId=2354243950, uKey=[-81, -50, 99, 65, -42, -11, -22, -19, -16, 36, -72, 72, -70, -10, -113, 0, -99, 5, 97, -26, 36, 17, -45, -72, -83, -97, -57, -69, 53, 27, -6, 67, -7, 6, 57, 20, -106, 47, 81, 38, -86, -21, -102, 34, 34, 20, -12, -127, 25, -53, 106, -25, 89, 8, -75, 79, 33, -86, 22, 16, -99, 90, 123, 86, -46, -23, -70, 23, 76, -125, -109, -127, -46, -8, -51, 14, -118, 112, -128, -77, 34, 21, -70, -23, 15, 71, -50, 27, 15, 60, -42, -72, 88, -82, -17, 47, -29, -117, -107, 58, -82, -128, 4, -67, -23, 74, 25, 84, -23, -31, 67, -44, 34, -113, -4, 6, -122, 27, -18, 76, -109, -127, 44, 10, 66, 64, -128, 42])
 13:46:18 [INFO] [NETWORK] [Highway] Uploading group image to 101.91.5.187:443, size=74.79 KiB
 13:46:32 [INFO] [NETWORK] [Highway] Uploading group image to 183.3.233.225:8080, size=0 B
 13:46:33 [INFO] [NETWORK] [Highway] Uploading group image to 123.150.76.170:80, size=0 B
 13:46:34 [INFO] [NETWORK] [Highway] Uploading group image to 163.177.92.121:443, size=0 B
 13:46:34 [ERROR] [CQHTTPMirai] java.lang.IllegalStateException: cannot upload group image, failed on all servers.
        at net.mamoe.mirai.qqandroid.network.highway.HighwayHelper.uploadImageToServers(HighwayHelper.kt:110)
        at net.mamoe.mirai.qqandroid.network.highway.HighwayHelper.uploadImageToServers(HighwayHelper.kt:95)
        at net.mamoe.mirai.qqandroid.contact.GroupImpl.uploadImage(GroupImpl.kt:428)
        at net.mamoe.mirai.qqandroid.contact.GroupImpl$uploadImage$1.invokeSuspend(GroupImpl.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.FileNotFoundException: /tmp/tmp3774342385991792580.tmp (没有那个文件或目录)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at net.mamoe.mirai.utils.internal.AsReusableInput_jvmKt$asReusableInput$2.chunkedFlow(asReusableInput.jvm.kt:51)
        at net.mamoe.mirai.utils.internal.DeferredReusableInput.chunkedFlow(DeferredReusableInput.jvm.kt:40)
        at net.mamoe.mirai.qqandroid.network.highway.HighwayKt.createImageDataPacketSequence(highway.kt:45)
        at net.mamoe.mirai.qqandroid.network.highway.HighwayKt.createImageDataPacketSequence$default(highway.kt:40)
        at net.mamoe.mirai.qqandroid.network.highway.HighwayHelper.uploadImage$mirai_core_qqandroid(HighwayHelper.kt:159)
        at net.mamoe.mirai.qqandroid.network.highway.HighwayHelper$uploadImageToServers$$inlined$retryWithServers$1.invokeSuspend(HighwayHelper.kt:231)
        at net.mamoe.mirai.qqandroid.network.highway.HighwayHelper$uploadImageToServers$$inlined$retryWithServers$1.invoke(HighwayHelper.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
        at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:120)
        at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:83)
        at net.mamoe.mirai.qqandroid.network.highway.HighwayHelper.uploadImageToServers(HighwayHelper.kt:232)
        ... 12 more

看上去好像不是hoshinobot的问题，好像是上传服务器的错……但是base64协议和file协议发本地setu都没事，只有抽卡会报错
希望能帮我解惑，谢谢

**Comment by zangxx66** [comment]
我是十连会报错，单抽没有问题

**Comment by yuban01652** [comment]
我这里抽十连和一井都有概率报错，有概率正常。并且把图片部分的代码注释掉，只发送文字，不会出错。

**Comment by zangxx66** [comment]
> 我这里抽十连和一井都有概率报错，有概率正常。并且把图片部分的代码注释掉，只发送文字，不会出错。

请问哪部分是可以注释掉的，只需要文字也可以了，pro到期后我估计这bot也没法回到air状态继续用

**Comment by yuban01652** [comment]
看gacha里的init.py，十连的话，if sv.bot.config.USE_CQPRO一直到else这部分注释，
一井的话，竟然没有三星？这个后面else的部分注释，加两行
res = [f'{c.name}' for c in res]
res = '\n'.join(res)

**Comment by Ice-Cirno** [comment]
错误原因应该是这里：
Caused by: java.io.FileNotFoundException: /tmp/tmp3774342385991792580.tmp (没有那个文件或目录)
这应该和mirai的发图机制有关，不属于hoshino本体的问题，请检查你的mirai配置。
