### ISSUE TITLE
卡池挂了

### ISSUE THREAD

**Issue by Naexen** [Ice-Cirno/HoshinoBot#168]
[2020-12-18 15:37:49,683 nonebot] ERROR: Failed to import "hoshino.modules.priconne.gacha", error: Expecting value: line 1 column 1 (char 0)
[2020-12-18 15:37:49,683 nonebot] ERROR: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "D:\app\python384\lib\site-packages\nonebot\plugin.py", line 249, in load_plugin
    module = importlib.import_module(module_path)
  File "D:\app\python384\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\HoshinoBot\hoshino\modules\priconne\gacha\__init__.py", line 38, in <module>
    _group_pool = json.load(f)
  File "D:\app\python384\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "D:\app\python384\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\app\python384\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\app\python384\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Ice-Cirno** [comment]
检查卡池的config.json
