### ISSUE TITLE
matplotlib更新导致启动失败

### ISSUE THREAD

**Issue by Cathgao** [Ice-Cirno/HoshinoBot#174]
```
Traceback (most recent call last):
  File "C:\Users\gao\Desktop\HoshinoBot\run.py", line 1, in <module>
    import hoshino
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\__init__.py", line 54, in <module>
    from . import R
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\R.py", line 9, in <module>
    from hoshino import logger, util
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\util\__init__.py", line 12, in <module>
    from matplotlib import pyplot as plt
  File "C:\Users\gao\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\__init__.py", line 174, in <module>
    _check_versions()
  File "C:\Users\gao\AppData\Local\Programs\Python\Python39\lib\site-packages\matplotlib\__init__.py", line 159, in _check_versions
    from . import ft2font
ImportError: DLL load failed while importing ft2font: 找不到指定的模块。
```
目前可以降级matplotlib来暂时解决
`pip install matplotlib==3.2.0`

**Comment by Cathgao** [comment]
若是python3.9，下载3.2.2的whl安装包也可以
