### ISSUE TITLE
nonebot库更新，造成lssv命令无法正常使用

### ISSUE THREAD

**Issue by shadow7755** [Ice-Cirno/HoshinoBot#190]
按照requirements里的更新，更新了Python依赖，lssv命令无法正常使用了
报错日志 

[2021-07-19 06:07:23,990 nonebot] ERROR: An exception occurred while running command ('lssv',):
[2021-07-19 06:07:23,990 nonebot] ERROR: 'CommandSession' object has no attribute 'args'
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\command\__init__.py", line 866, in _real_run_command
    await asyncio.wait_for(future, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\command\__init__.py", line 164, in run
    await self.args_parser_func(session)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin.py", line 390, in shell_like_args_parser
    session.args['argv'] = shlex.split(session.current_arg)
AttributeError: 'CommandSession' object has no attribute 'args'

**Comment by Ice-Cirno** [comment]
先降级到nonebot 1.8.2吧
```sh
pip3 install nonebot==1.8.2
```

这属于nonebot的锅，已向那边提issue
https://github.com/nonebot/nonebot/issues/271

**Comment by Cathgao** [comment]
请问一下，升级到nonebot1.8.4依然无效，是什么问题呢？

**Comment by Cathgao** [comment]
请问一下，升级到nonebot1.8.4依然无效，是什么问题呢？

**Comment by Cathgao** [comment]
没有报错，就单纯的当成普通消息忽略了
