### ISSUE TITLE
Linux服务器上报错

### ISSUE THREAD

**Issue by vaqua** [Ice-Cirno/HoshinoBot#199]
```py
[root@VM-0-16-centos HoshinoBot]# poetry run python run.py
[2021-09-06 21:56:18,782 config] INFO: Succeeded to load config of "dice"
[2021-09-06 21:56:18,783 config] INFO: Succeeded to load config of "priconne"
[2021-09-06 21:56:18,783 config] INFO: Succeeded to load config of "groupmaster"
[2021-09-06 21:56:18,783 config] INFO: Succeeded to load config of "botmanage"
[2021-09-06 21:56:18,783 config] INFO: Succeeded to load config of "pcrclanbattle"
Traceback (most recent call last):
  File "/root/pcrbot/HoshinoBot/run.py", line 1, in <module>
    import hoshino
  File "/root/pcrbot/HoshinoBot/hoshino/__init__.py", line 8, in <module>
    from .service import Service, sucmd
  File "/root/pcrbot/HoshinoBot/hoshino/service.py", line 14, in <module>
    from hoshino import log, priv, trigger
  File "/root/pcrbot/HoshinoBot/hoshino/priv.py", line 10, in <module>
    from hoshino.typing import CQEvent
  File "/root/pcrbot/HoshinoBot/hoshino/typing.py", line 8, in <module>
    from . import HoshinoBot
ImportError: cannot import name 'HoshinoBot' from partially initialized module 'hoshino' (most likely due to a circular import) (/root/pcrbot/HoshinoBot/hoshino/__init__.py)
```
参照<Linux 下部署一个公主连结 qq 群聊机器人>这篇文章部署HoshinoBot和go-cqhttp,依赖已经装好了,go-cqhttp能跑起来了.
但是HoshinoBot报错了,Google搜了自己也研究了很久实在解决不了,请问大佬这是什么原因导致的报错？

**Comment by Ice-Cirno** [comment]
重新pull一下，已修
