### ISSUE TITLE
最新代码拉下来运行报错

### ISSUE THREAD

**Issue by zh616110538** [Ice-Cirno/HoshinoBot#209]
```
root@39adaf213598:/opt# python run.py
Traceback (most recent call last):
  File "/opt/run.py", line 1, in <module>
    import hoshino
  File "/opt/hoshino/__init__.py", line 9, in <module>
    from . import log, config, util
ImportError: cannot import name 'config' from partially initialized module 'hoshino' (most likely due to a circular import) (/opt/hoshino/__init__.py)
```

python版本是3.10.0
```
root@39adaf213598:/opt# python --version
Python 3.10.0
```

**Comment by zh616110538** [comment]
忘记复制config目录了
