### ISSUE TITLE
发不了图片

### ISSUE THREAD

**Issue by 0bug0** [Ice-Cirno/HoshinoBot#222]
两个插件的问题
网抑云：
INFO: Message 1503465804 triggered net_ease_cloud_word.
ERROR: <class 'aiocqhttp.exceptions.ActionFailed'> occured when net_ease_cloud_word handling message -939948817.
ERROR: <ActionFailed data=None, echo={'seq': 3}, msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考 go-cqhttp 端输出'>
Traceback (most recent call last):
  File "/root/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/root/HoshinoBot/hoshino/modules/hiumsentences/hiumsentences.py", line 58, in net_ease_cloud_word
    await bot.send(ev, sentences)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 271, in send
    return await self.send_msg(**params)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 238, in call_action
    return await self._api.call_action(action=action, **params)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 178, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 153, in call_action
    return _handle_api_result(await
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 38, in _handle_api_result
    raise ActionFailed(result=result)
aiocqhttp.exceptions.ActionFailed: <ActionFailed data=None, echo={'seq': 3}, msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考 go-cqhttp 端输出'>

马娘：
INFO: Message 781853146 triggered caculate.
ERROR: <class 'ValueError'> occured when caculate handling message 781853146.
ERROR: list.remove(x): x not in list
Traceback (most recent call last):
  File "/root/HoshinoBot/hoshino/msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "/root/HoshinoBot/hoshino/modules/uma_plugin/uma_compatibility/__init__.py", line 62, in caculate
    self = judge_name(text_list[0], f_data, replace_data)
  File "/root/HoshinoBot/hoshino/modules/uma_plugin/uma_compatibility/caculate.py", line 4, in judge_name
    name_list.remove('current_chara')
ValueError: list.remove(x): x not in list
想问下是哪里出了问题

**Comment by Ice-Cirno** [comment]
非原生插件请去相应的项目提问
