### ISSUE TITLE
__init__.py报错

### ISSUE THREAD

**Issue by SouthernDreamS6** [Ice-Cirno/HoshinoBot#225]
ash-4.3# python3.8 run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    import hoshino
  File "/volume1/Documents/HoshinoBot/hoshino/__init__.py", line 5, in <module>
    import nonebot
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/nonebot/__init__.py", line 5, in <module>
    import aiocqhttp
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 19, in <module>
    from quart import Quart, request, abort, jsonify, websocket, Response
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/quart/__init__.py", line 3, in <module>
    from jinja2 import escape, Markup
ImportError: cannot import name 'escape' from 'jinja2' (/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/jinja2/__init__.py)
ash-4.3#

**Comment by CMHopeSunshine** [comment]
降级jinja2
`pip install jinja2==3.0.3 -U`

**Comment by SouthernDreamS6** [comment]
非常感谢，已成功运行！
