### ISSUE TITLE
反并发以及屏蔽关键词功能报错

### ISSUE THREAD

**Issue by kcn3388** [Ice-Cirno/HoshinoBot#230]
console log如下：
```
[2022-04-13 19:37:21,410 nonebot] INFO: Scheduler started
[hoshino_training] load module anti-holo failed
Traceback (most recent call last):
  File "/root/bot/XCW/Hoshino/hoshino/modules/hoshino_training/training.py", line 20, in load_functions
    importlib.import_module('hoshino.modules.hoshino_training.functions.' + name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/bot/XCW/Hoshino/hoshino/modules/hoshino_training/functions/anti-holo.py", line 53, in <module>
    keyword_replace(SB_HOLO, anti_holo)
  File "/root/bot/XCW/Hoshino/hoshino/modules/hoshino_training/util/keyword.py", line 11, in keyword_replace
    rex.allkw[k].func = func
AttributeError: 'list' object has no attribute 'func'
[hoshino_training] load module comic successed
[2022-04-13 19:37:21,415 反并发] INFO: Scheduled job add_trigger_words_wrapper_job start.
[2022-04-13 19:37:21,415 反并发] ERROR: <class 'AttributeError'> occured when doing scheduled job add_trigger_words_wrapper_job.
[2022-04-13 19:37:21,415 反并发] ERROR: 'list' object has no attribute 'func'
Traceback (most recent call last):
  File "/root/bot/XCW/Hoshino/hoshino/service.py", line 349, in wrapper
    ret = await func()
  File "/root/bot/XCW/Hoshino/hoshino/modules/anticoncurrency/anti_concurrency.py", line 75, in add_trigger_words_wrapper_job
    await add_trigger_words_wrapper()
  File "/root/bot/XCW/Hoshino/hoshino/modules/anticoncurrency/anti_concurrency.py", line 68, in add_trigger_words_wrapper
    sf.func = sf_wrapper(sf.func, trigger_group_index, trigger_word)
AttributeError: 'list' object has no attribute 'func'
```

**Comment by Ice-Cirno** [comment]
非原生插件的bug请提交至相应repo
