### ISSUE TITLE
关于不能自动回复

### ISSUE THREAD

**Issue by eachbol2333** [Ice-Cirno/HoshinoBot#232]
kihaku@ikihaku:~/HoshinoBot$ python3.8 run.py
ujson module not found, using json
msgpack not installed, MsgPackSerializer unavailable
[2022-05-31 15:04:02,680 config] INFO: Succeeded to load config of "groupmaster"
[2022-05-31 15:04:02,680 config] WARNING: Not found config of "dice"
[2022-05-31 15:04:02,680 config] WARNING: Not found config of "botmanage"
[2022-05-31 15:04:02,681 config] INFO: Succeeded to load config of "priconne"
[2022-05-31 15:04:02,681 config] INFO: Succeeded to load config of "pcrclanbattle"
[2022-05-31 15:04:02,995 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.random_repeater"
[2022-05-31 15:04:03,032 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.anti_lex"
[2022-05-31 15:04:03,037 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.sleeping_set"
[2022-05-31 15:04:03,037 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.group_notice"
[2022-05-31 15:04:03,037 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.anti_holo"
[2022-05-31 15:04:03,038 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.anti_asoul"
[2022-05-31 15:04:03,039 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.chat"
[2022-05-31 15:04:03,093 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.antiqks"
[2022-05-31 15:04:03,094 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.anti_abuse"
[2022-05-31 15:04:03,094 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.join_approve"
[2022-05-31 15:04:03,094 nonebot] INFO: Succeeded to import "hoshino.modules.groupmaster.anti_msg_recall"
[2022-05-31 15:04:03,095 nonebot] INFO: Succeeded to import "hoshino.modules.dice.dice"
[2022-05-31 15:04:03,097 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.ls"
[2022-05-31 15:04:03,097 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.billing"
[2022-05-31 15:04:03,097 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.group_invite"
[2022-05-31 15:04:03,098 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.data_cleaner"
[2022-05-31 15:04:03,098 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.group_leave"
[2022-05-31 15:04:03,098 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.feedback"
[2022-05-31 15:04:03,099 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.service_manage"
[2022-05-31 15:04:03,099 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.broadcast"
[2022-05-31 15:04:03,099 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.get_cqcode"
[2022-05-31 15:04:03,099 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.alert"
[2022-05-31 15:04:03,100 nonebot] INFO: Succeeded to import "hoshino.modules.botmanage.help"
/home/ikihaku/.local/lib/python3.8/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
[2022-05-31 15:04:03,137 hoshino] ERROR: 缺少图片资源：./res/img/priconne/gadget/equip.png
[2022-05-31 15:04:03,137 chara] ERROR: [Errno 2] No such file or directory: './res/img/priconne/gadget/equip.png'
Traceback (most recent call last):
  File "/home/ikihaku/HoshinoBot/hoshino/modules/priconne/chara.py", line 19, in <module>
    gadget_equip = R.img('priconne/gadget/equip.png').open()
  File "/home/ikihaku/HoshinoBot/hoshino/R.py", line 50, in open
    return Image.open(self.path)
  File "/home/ikihaku/.local/lib/python3.8/site-packages/PIL/Image.py", line 3068, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './res/img/priconne/gadget/equip.png'
[2022-05-31 15:04:03,151 nonebot] INFO: Succeeded to import "hoshino.modules.priconne.chara"
[2022-05-31 15:04:03,153 nonebot] INFO: Succeeded to import "hoshino.modules.priconne.query"
[2022-05-31 15:04:03,156 nonebot] INFO: Succeeded to import "hoshino.modules.priconne.games"
[2022-05-31 15:04:03,157 nonebot] INFO: Succeeded to import "hoshino.modules.priconne.comic"
[2022-05-31 15:04:03,157 nonebot] INFO: Succeeded to import "hoshino.modules.priconne.pcr_data_updater"
[2022-05-31 15:04:03,202 nonebot] INFO: Succeeded to import "hoshino.modules.priconne.news"
[2022-05-31 15:04:03,203 gacha] WARNING: group_pool_config.json not found, will create when needed.
[2022-05-31 15:04:03,204 nonebot] INFO: Succeeded to import "hoshino.modules.priconne.gacha"
[2022-05-31 15:04:03,205 nonebot] INFO: Succeeded to import "hoshino.modules.priconne.cherugo"
[2022-05-31 15:04:03,205 nonebot] INFO: Succeeded to import "hoshino.modules.priconne.login_bonus"
[2022-05-31 15:04:03,206 nonebot] INFO: Succeeded to import "hoshino.modules.priconne.arena_reminder"
[2022-05-31 15:04:03,212 pcr-arena] WARNING: arena_db.json not found, will create when needed.
[2022-05-31 15:04:03,212 hoshino] ERROR: 缺少图片资源：./res/img/priconne/gadget/thumb-up-i.png
[2022-05-31 15:04:03,212 pcr-arena] ERROR: [Errno 2] No such file or directory: './res/img/priconne/gadget/thumb-up-i.png'
Traceback (most recent call last):
  File "/home/ikihaku/HoshinoBot/hoshino/modules/priconne/arena/__init__.py", line 31, in <module>
    thumb_up_i = R.img('priconne/gadget/thumb-up-i.png').open().resize((16, 16), Image.LANCZOS)
  File "/home/ikihaku/HoshinoBot/hoshino/R.py", line 50, in open
    return Image.open(self.path)
  File "/home/ikihaku/.local/lib/python3.8/site-packages/PIL/Image.py", line 3068, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './res/img/priconne/gadget/thumb-up-i.png'
[2022-05-31 15:04:03,213 nonebot] INFO: Succeeded to import "hoshino.modules.priconne.arena"
[2022-05-31 15:04:03,213 nonebot] INFO: Succeeded to import "hoshino.modules.pcrclanbattle.hedao"
[2022-05-31 15:04:03,214 nonebot] INFO: Succeeded to import "hoshino.modules.pcrclanbattle.version_selector"
[2022-05-31 15:04:03,218 nonebot] INFO: Succeeded to import "hoshino.modules.pcrclanbattle.clanbattle"
[2022-05-31 15:04:03,218 nonebot] INFO: Running on 127.0.0.1:8080
 * Serving Quart app ''
 * Environment: production
 * Please use an ASGI server (e.g. Hypercorn) directly in production
 * Debug mode: False
 * Running on http://127.0.0.1:8080 (CTRL + C to quit)
[2022-05-31 15:04:03,220 nonebot] INFO: Scheduler started
[2022-05-31 15:04:03,220] Running on http://127.0.0.1:8080 (CTRL + C to quit)
[2022-05-31 15:04:35,017] 127.0.0.1:39756 GET /ws/ 1.1 101 - 1465
[2022-05-31 15:04:47,044 nonebot] INFO: Self: 2790229640, Message -1047012570 from 1658276637: '在？'
![image](https://user-images.githubusercontent.com/105063888/171103951-c62e94eb-8d17-4964-9380-c96767188fd3.png)
运行之后没法自动回复，Linux系统，请问是哪里设置没对吗

**Comment by clacknya** [comment]
https://github.com/Ice-Cirno/HoshinoBot/blob/e5a1881102060f59544141f62b26497d2a76a42e/hoshino/modules/groupmaster/chat.py#L8-L11

你可能用了半角符号

**Comment by eachbol2333** [comment]
解决了，Ubuntu好像不能用/作为command命令
