### ISSUE TITLE
按照部署教程运行run.py后报错

### ISSUE THREAD

**Issue by tietiejian** [Ice-Cirno/HoshinoBot#237]
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    import hoshino
  File "/home/ubuntu/robbit/HoshinoBot/hoshino/__init__.py", line 5, in <module>
    import nonebot
  File "/usr/local/lib/python3.8/dist-packages/nonebot/__init__.py", line 5, in <module>
    import aiocqhttp
  File "/usr/local/lib/python3.8/dist-packages/aiocqhttp/__init__.py", line 19, in <module>
    from quart import Quart, request, abort, jsonify, websocket, Response
  File "/usr/local/lib/python3.8/dist-packages/quart/__init__.py", line 7, in <module>
    from .app import Quart
  File "/usr/local/lib/python3.8/dist-packages/quart/app.py", line 46, in <module>
    from .asgi import ASGIHTTPConnection, ASGILifespan, ASGIWebsocketConnection
  File "/usr/local/lib/python3.8/dist-packages/quart/asgi.py", line 29, in <module>
    from .debug import traceback_response
  File "/usr/local/lib/python3.8/dist-packages/quart/debug.py", line 6, in <module>
    from jinja2 import Template
  File "/home/ubuntu/.local/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/home/ubuntu/.local/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/home/ubuntu/.local/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/home/ubuntu/.local/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/ubuntu/.local/lib/python3.8/site-packages/markupsafe/__init__.py)

**Comment by tietiejian** [comment]
安装依赖时也有报错
ERROR: quart 0.17.0 has requirement werkzeug>=2.0.0, but you'll have werkzeug 1.0.1 which is incompatible.
ERROR: httpcore 0.15.0 has requirement h11<0.13,>=0.11, but you'll have h11 0.13.0 which is incompatible.
ERROR: cattrs 1.10.0 has requirement attrs>=20, but you'll have attrs 19.3.0 which is incompatible.
ERROR: requests-cache 0.9.4 has requirement attrs<22.0,>=21.2, but you'll have attrs 19.3.0 which is incompatible.

**Comment by Ice-Cirno** [comment]
依赖库版本问题。卸载报错信息中报错的包，重新按requirements.txt中的版本安装；或使用虚拟环境。
