### ISSUE TITLE
请问这是什么情况

### ISSUE THREAD

**Issue by dgkkjt** [Ice-Cirno/HoshinoBot#245]
开启arena后会报错
SyntaxError: invalid syntax
[2022-08-25 06:38:06,935 nonebot] ERROR: Failed to import "hoshino.modules.priconne.arena", error: invalid syntax (<fstring>, line 1)
[2022-08-25 06:38:06,936 nonebot] ERROR: invalid syntax (<fstring>, line 1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/nonebot/plugin.py", line 263, in load_plugin
    module = importlib.import_module(module_path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/HoshinoBot/hoshino/modules/priconne/arena/__init__.py", line 21, in <module>
    from . import arena
  File "<fstring>", line 1
    (payload=)
            ^
SyntaxError: invalid syntax

**Comment by Ice-Cirno** [comment]
请用python3.8
