### ISSUE TITLE
安装后无法运行

### ISSUE THREAD

**Issue by suansuanru9999** [Ice-Cirno/HoshinoBot#248]
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    import hoshino
  File "/root/HoshinoBot/hoshino/__init__.py", line 5, in <module>
    import nonebot
  File "/usr/local/lib/python3.8/dist-packages/nonebot/__init__.py", line 5, in <module>
    import aiocqhttp
  File "/usr/local/lib/python3.8/dist-packages/aiocqhttp/__init__.py", line 19, in <module>
    from quart import Quart, request, abort, jsonify, websocket, Response
  File "/usr/local/lib/python3.8/dist-packages/quart/__init__.py", line 5, in <module>
    from .app import Quart as Quart
  File "/usr/local/lib/python3.8/dist-packages/quart/app.py", line 49, in <module>
    from .asgi import ASGIHTTPConnection, ASGILifespan, ASGIWebsocketConnection
  File "/usr/local/lib/python3.8/dist-packages/quart/asgi.py", line 29, in <module>
    from .debug import traceback_response
  File "/usr/local/lib/python3.8/dist-packages/quart/debug.py", line 8, in <module>
    from .wrappers import Response
  File "/usr/local/lib/python3.8/dist-packages/quart/wrappers/__init__.py", line 3, in <module>
    from .base import BaseRequestWebsocket
  File "/usr/local/lib/python3.8/dist-packages/quart/wrappers/base.py", line 7, in <module>
    from werkzeug.sansio.request import Request as SansIORequest
ModuleNotFoundError: No module named 'werkzeug.sansio'

查了半天没有找到解决办法，有知道的能解答一下吗

**Comment by suansuanru9999** [comment]
werkzeug装了1.0.1是上面这样，装了2.2.0是
File "run.py", line 1, in <module>
    import hoshino
  File "/root/HoshinoBot/hoshino/__init__.py", line 5, in <module>
    import nonebot
  File "/usr/local/lib/python3.8/dist-packages/nonebot/__init__.py", line 5, in <module>
    import aiocqhttp
  File "/usr/local/lib/python3.8/dist-packages/aiocqhttp/__init__.py", line 19, in <module>
    from quart import Quart, request, abort, jsonify, websocket, Response
  File "/usr/local/lib/python3.8/dist-packages/quart/__init__.py", line 5, in <module>
    from .app import Quart as Quart
  File "/usr/local/lib/python3.8/dist-packages/quart/app.py", line 49, in <module>
    from .asgi import ASGIHTTPConnection, ASGILifespan, ASGIWebsocketConnection
  File "/usr/local/lib/python3.8/dist-packages/quart/asgi.py", line 29, in <module>
    from .debug import traceback_response
  File "/usr/local/lib/python3.8/dist-packages/quart/debug.py", line 6, in <module>
    from jinja2 import Template
  File "/usr/local/lib/python3.8/dist-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/local/lib/python3.8/dist-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.8/dist-packages/markupsafe/__init__.py)

**Comment by Ice-Cirno** [comment]
尝试一下
Quart==0.14.1
Werkzeug==1.0.1
