### ISSUE TITLE
启动机器人失败

### ISSUE THREAD

**Issue by UWDBW** [Ice-Cirno/HoshinoBot#253]
Traceback (most recent call last):
  File "F:\novelai\pzwj\HoshinoBot\run.py", line 1, in <module>
    import hoshino
  File "F:\novelai\pzwj\HoshinoBot\hoshino\__init__.py", line 5, in <module>
    import nonebot
  File "C:\Users\LJX\AppData\Roaming\Python\Python39\site-packages\nonebot\__init__.py", line 7, in <module>
    import aiocqhttp
  File "C:\Users\LJX\AppData\Roaming\Python\Python39\site-packages\aiocqhttp\__init__.py", line 19, in <module>
    from quart import Quart, request, abort, jsonify, websocket, Response
  File "C:\Users\LJX\AppData\Roaming\Python\Python39\site-packages\quart\__init__.py", line 5, in <module>
    from .app import Quart as Quart
  File "C:\Users\LJX\AppData\Roaming\Python\Python39\site-packages\quart\app.py", line 39, in <module>
    from hypercorn.asyncio import serve
  File "C:\Users\LJX\AppData\Roaming\Python\Python39\site-packages\hypercorn\asyncio\__init__.py", line 6, in <module>
    from .run import worker_serve
  File "C:\Users\LJX\AppData\Roaming\Python\Python39\site-packages\hypercorn\asyncio\run.py", line 16, in <module>
    from .tcp_server import TCPServer
  File "C:\Users\LJX\AppData\Roaming\Python\Python39\site-packages\hypercorn\asyncio\tcp_server.py", line 11, in <module>
    from ..protocol import ProtocolWrapper
  File "C:\Users\LJX\AppData\Roaming\Python\Python39\site-packages\hypercorn\protocol\__init__.py", line 5, in <module>
    from .h2 import H2Protocol
  File "C:\Users\LJX\AppData\Roaming\Python\Python39\site-packages\hypercorn\protocol\h2.py", line 23, in <module>
    from .ws_stream import WSStream
  File "C:\Users\LJX\AppData\Roaming\Python\Python39\site-packages\hypercorn\protocol\ws_stream.py", line 9, in <module>
    from wsproto.connection import Connection, ConnectionState, ConnectionType
  File "C:\Users\LJX\AppData\Roaming\Python\Python39\site-packages\wsproto\__init__.py", line 9, in <module>
    from .connection import Connection, ConnectionState, ConnectionType
  File "C:\Users\LJX\AppData\Roaming\Python\Python39\site-packages\wsproto\connection.py", line 23, in <module>
    from .utilities import LocalProtocolError
  File "C:\Users\LJX\AppData\Roaming\Python\Python39\site-packages\wsproto\utilities.py", line 12, in <module>
    from h11._headers import Headers as H11Headers
ImportError: cannot import name 'Headers' from 'h11._headers' (C:\Users\LJX\AppData\Roaming\Python\Python39\site-packages\h11\_headers.py)

**Comment by Ice-Cirno** [comment]
尝试更换依赖版本
```bash
pip install MarkupSafe~=1.0 Jinja2~=2.11.2 h11==0.12.0
```

**Comment by UWDBW** [comment]
ModuleNotFoundError: No module named 'werkzeug.sansio'

**Comment by UWDBW** [comment]
pip install aiocqhttp~=1.4.0，Defaulting to user installation because normal site-packages is not writeable，然后自动给我装了Successfully installed markupsafe-2.1.1 werkzeug-2.2.2

**Comment by UWDBW** [comment]
然后我把aiocqhttp版本降了，有日志出现，现在是[2022-10-18 09:43:42,805 hoshino] ERROR: 缺少图片资源：./res/img\priconne\gadget\equip.png'和FileNotFoundError: [Errno 2] No such file or directory: './res/img\\priconne\\comic\\index.json'

**Comment by UWDBW** [comment]
连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connectex: No connection could be made because the target machine actively refused it.
